api_key_path ENV["ASC_API_KEY_PATH"] || "/tmp/asc_api_key.json"
app_identifier "ro.summersmile.sudoku"

skip_binary_upload true
skip_screenshots true
skip_metadata false
force true
overwrite_screenshots false
phased_release false
automatic_release false

submission_information({
  add_id_info_uses_idfa: true,
  add_id_info_serves_ads: true,
  add_id_info_tracks_install: true,
  add_id_info_tracks_action: false,
  add_id_info_limits_tracking: true,
  export_compliance_encryption_updated: false,
  export_compliance_uses_encryption: false,
  content_rights_contains_third_party_content: false
})
